[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
src_dir = .
build_src_filter = +<MiniTV_Ultra.ino>
board_build.flash_size = 4MB
board_build.partitions = default.csv
